import type { Metadata } from "next";
import { Comfortaa, Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + "h-full"}>
        <div className="w-full min-h-screen bg-zinc-900">
          <div className="static flex justify-left align-middle m-0 p-0 gap-x-2 bg-zinc-800">
            <Image
              className="m-2"
              src="/right-bite-logo.png"
              alt="RightBite Logo"
              width={75}
              height={75}
              priority
            />
            <h1 className="my-6 text-4xl text-white font-bold">RightBite</h1>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
